#filename:.travis.yml
dist: bionic
sudo: false
notifications:
  email: false
env:
  global:
  - REPO=tool
before_script:
- export TZ=Asia/Shanghai
script:
- mkdir -p $TRAVIS_BUILD_DIR/output
- chmod +x ./gfwlist2ros.sh && ./gfwlist2ros.sh && mv ./gfwlist_domain.rsc ./output
- chmod +x ./cnlist2ros.sh && ./cnlist2ros.sh && mv ./all_cn_cidr.rsc ./output
- chmod +x ./gfwlist2smartdns.sh && ./gfwlist2smartdns.sh && mv ./gfwlist_domain.conf ./output
- chmod +x ./cnlist2smartdns.sh && ./cnlist2smartdns.sh && mv ./china_domain.conf ./output
- chmod +x ./nfaws2ros.sh && ./nfaws2ros.sh && mv ./nfaws.rsc ./output
- DATE_TIME=$(date "+%Y-%m-%d %H:%M:%S")
- cd /tmp/
- git clone https://${GIT_USER}:${TOKEN}@github.com/${GIT_USER}/${REPO}.git --branch gh-pages --single-branch gh-pages > /dev/null 2>&1 || exit 1
- cd gh-pages || exit 1
- git config user.name "easongao"
- git config user.email "littlegao7@gmail.com"
- cp $TRAVIS_BUILD_DIR/output/* .
- git add -A
- git commit -a -m "Configuration Files Generated on [$DATE_TIME]"
- git push -fq origin gh-pages > /dev/null 2>&1 || exit 1
- echo -e "Uploaded files to gh-pages\n"
